# Generated by Django 5.1.4 on 2025-02-01 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('insurance_type', models.CharField(choices=[('HDHP', 'High Deductible Health Plan'), ('PPO', 'Preferred Provider Organization'), ('HMO', 'Health Maintenance Organization'), ('MEDICARE', 'Medicare'), ('MEDICAID', 'Medicaid')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('out_of_pocket_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profiles', to='accounts.member')),
            ],
            options={
                'ordering': ['-is_primary', 'effective_date'],
                'unique_together': {('member', 'policy_number')},
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('service_category', models.CharField(choices=[('GENERAL', 'General Medical'), ('EMERGENCY', 'Emergency Care'), ('PHARMACY', 'Pharmacy'), ('SPECIALIST', 'Specialist Care'), ('DIAGNOSTIC', 'Diagnostic Services'), ('CUSTOM', 'Custom Service')], default='GENERAL', max_length=20)),
                ('coverage_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('copay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_preauth', models.BooleanField(default=False)),
                ('network_tier', models.CharField(choices=[('IN', 'In-Network'), ('OUT', 'Out-of-Network')], max_length=20)),
                ('insurance_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='insuranceprofile.insuranceprofile')),
            ],
            options={
                'unique_together': {('insurance_profile', 'service_type', 'network_tier')},
            },
        ),
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_npi', models.CharField(max_length=15)),
                ('network_status', models.CharField(choices=[('IN', 'In-Network'), ('OUT', 'Out-of-Network')], max_length=20)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('insurance_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_providers', to='insuranceprofile.insuranceprofile')),
            ],
            options={
                'unique_together': {('insurance_profile', 'provider_npi')},
            },
        ),
    ]
